"use client";

import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Plus, Minus } from "lucide-react";

const faqs = [
  {
    question: "What platforms does Botifyme support?",
    answer: "Botifyme seamlessly integrates with WhatsApp, Facebook Messenger, Instagram, and provides a customizable Web Chat widget for your own store. You can manage all conversations from one unified inbox. Botify provides a free storefront website on your domain as well."
  },
  {
    question: "How does the message limit work in the pricing?",
    answer: "Each plan comes with a 'Total Messages' limit and an 'AI Replies' limit. 'Total Messages' counts all incoming and outgoing texts. The 'AI Replies' are specifically the automated responses generated by our smart bot to close sales without your intervention."
  },
  {
    question: "Can a human agent take over the conversation?",
    answer: "Absolutely! Botifyme offers a seamless human hand-off feature. If the AI cannot answer a complex query or if the user requests human support, it immediately pauses the bot and notifies your team to step in."
  },
  {
    question: "How does the Logistics & Delivery integration work?",
    answer: "We have built-in integrations with PickNDrop and NCM logistics. You can automatically assign delivery branches and track order statuses right from the chat dashboard, updating your customers in real-time."
  },
  {
    question: "Do I need coding skills to set this up?",
    answer: "No coding is required. You can connect your Facebook/WhatsApp business accounts with just a few clicks, and our system automatically syncs your product catalog to start answering queries immediately."
  },
  {
    question: "Can I host the e-commerce store on my own domain?",
    answer: "Yes, we provide custom domain deployment! You can host the fully-featured Botifyme e-commerce site directly on your own custom domain (e.g., shop.yourdomain.com) for a completely branded experience."
  }
];

export default function FAQ() {
  const [openIndex, setOpenIndex] = useState<number | null>(0);

  const toggleFaq = (index: number) => {
    setOpenIndex(openIndex === index ? null : index);
  };

  return (
    <section id="faq" className="py-16 sm:py-20 md:py-24 bg-slate-50 border-t border-slate-200 px-4 sm:px-6">
      <div className="container mx-auto max-w-4xl">
        <motion.div 
          className="text-center mb-12 md:mb-16"
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
        >
          <h2 className="text-3xl md:text-4xl font-bold mb-4 text-slate-900">Frequently Asked <span className="text-gradient">Questions</span></h2>
          <p className="text-slate-600 text-base md:text-lg">Everything you need to know about Botifyme.</p>
        </motion.div>

        <div className="space-y-4">
          {faqs.map((faq, index) => (
            <motion.div 
              key={index}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ delay: index * 0.1 }}
              className="bg-white border border-slate-200 rounded-2xl overflow-hidden shadow-sm hover:shadow-md transition-shadow"
            >
              <button
                className="w-full px-6 py-5 text-left flex items-center justify-between focus:outline-none"
                onClick={() => toggleFaq(index)}
              >
                <span className="font-bold text-slate-900 pr-4">{faq.question}</span>
                <div className={`shrink-0 w-8 h-8 rounded-full flex items-center justify-center transition-colors ${openIndex === index ? 'bg-purple-100 text-purple-600' : 'bg-slate-100 text-slate-400'}`}>
                  {openIndex === index ? <Minus className="w-4 h-4" /> : <Plus className="w-4 h-4" />}
                </div>
              </button>
              <AnimatePresence>
                {openIndex === index && (
                  <motion.div
                    initial={{ height: 0, opacity: 0 }}
                    animate={{ height: "auto", opacity: 1 }}
                    exit={{ height: 0, opacity: 0 }}
                    transition={{ duration: 0.3, ease: "easeInOut" }}
                  >
                    <div className="px-6 pb-5 text-slate-600 leading-relaxed text-sm md:text-base border-t border-slate-100 mt-2 pt-4">
                      {faq.answer}
                    </div>
                  </motion.div>
                )}
              </AnimatePresence>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  );
}
